use_frameworks!

platform :ios, '10.0'

target 'YFAlertController_Example' do
  pod 'YFAlertController', :path => '../'

  target 'YFAlertController_Tests' do
    inherit! :search_paths

    
  end
end
